export const siteConfig = {
  name: "Paliwal Secure AI",
  alternateName: "InsureGPT",
  url: "https://paliwalsecure.in",
  ogImage: "https://paliwalsecure.in/og-image.jpg",
  description:
    "India's AI-powered insurance advisor. Compare health insurance, motor insurance, EV insurance, term life and travel insurance. IRDAI-regulated products. By Himanshu Paliwal — POSP Code IP429834.",
  keywords: [
    "AI Insurance Advisor India",
    "Best Health Insurance India",
    "Car Insurance Renewal Online",
    "Health Insurance Comparison",
    "AI Insurance Recommendation",
    "Easy Insurance Claim Guide",
    "Motor Insurance India",
    "Life Insurance Advisor India",
    "Insurance AI Platform India",
    "Smart Insurance India",
    "Zero Dep Car Insurance",
    "Family Health Insurance",
    "InsureGPT",
    "EV Insurance India",
    "Insurance Comparison Tool",
    "Cashless Health Insurance",
    "IRDAI Certified Advisor",
    "Paliwal Secure AI",
    "Insurance Advisor Jaipur",
    "POSP Insurance Agent",
  ],
  pospCode: "IP429834",
  whatsapp: "+919257877312",
  email: "himanshu@paliwalsecure.in",
  domains: ["paliwalsecure.in", "paliwalsecure.com"],
  links: {
    twitter: "https://twitter.com/PaliwalSecureAI",
    linkedin: "https://linkedin.com/company/paliwal-secure-ai",
    instagram: "https://instagram.com/paliwalsecureai",
    youtube: "https://youtube.com/@PaliwalSecureAI",
  },
  author: {
    name: "Himanshu Paliwal",
    url: "https://paliwalsecure.in",
    credentials: "IRDAI Certified Insurance Advisor",
    pospCode: "IP429834",
  },
};
